app2/urls.py
from django.urls import path
from app2.views import *
app_name='app2'
urlpatterns=[
    path('bye/',bye,name='bye'),
]

app3/urls.py
from django.urls import path
from app3.views import *
app_name='asadapp'
urlpatterns=[
    path('asad/',asad,name='asad')
]

project9/urls.py
from django.contrib import admin
from django.urls import path,include
from app1.views import *
import app2,app3
urlpatterns = [
    path('admin/', admin.site.urls),
    path('hai/',hai,name='hai'),
    path('hello/',hello, name='hello'),
    path('bye/',include('app2.urls')),
    path('asad/',include('app3.urls')),
]

app1/models.py
from django.db import models

# Create your models here.

app2/models.py
from django.db import models

# Create your models here.

app3/models.py
from django.db import models

# Create your models here.

app1/views.py
from django.shortcuts import render

# Create your views here.
def hai(request):
    return render(request,'hai.html')
def hello(request):
    return render(request,'hello.html')

app2/views.py
from django.shortcuts import render

# Create your views here.
def bye(request):
    return render(request,'bye.html')

app3/views.py
from django.shortcuts import render

# Create your views here.
def asad(request):
    return render(request,'asad.html')

templates/asad.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>THIS IS ASAD'S PAGE</h1><br>
        <a href="{% url 'hai' %}">Go to hai file</a>

    </center>
</body>
</html>

templates/bye.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>This is our 3rd as well as bye html file</h1><br>
        <a href="{% url 'hai'%}">Go to hai file</a>
    </center>
</body>
</html>

templates/hai.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>This is our first hai html file</h1>
        <a href="{% url 'hello' %}">Navigate to hello file</a><br><br>
        <a href="{% url 'app2:bye' %}">Navigate to bye file</a><br><br>
        <a href="{% url 'asadapp:asad' %}">Go to asad's page</a>
    </center>
</body>
</html>

templates/hello.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>This is our 2nd file as well as hello file</h1>
        <h6><a href="{% url 'hai' %}">navigate to hai file</a></h6>
    </center>
</body>
</html>